### ISSUE TITLE
如何复现泰语的最好结果？

### ISSUE THREAD

**Issue by xhr-catcher** [zliucr/Crosslingual-NLU#1]
您好，请问应该如何复现论文中提到的最好结果呢？直接跑readme.md中的指令嘛？下图是我跑了几次后的结果，准确率和F1一直没有跑到和最好结果相当的数值。请问是否有特殊的参数设置才能跑到最好的结果吗？
![image](https://user-images.githubusercontent.com/49116661/84991625-5c8b1780-b179-11ea-8d4b-60ddf8dadb87.png)

**Comment by zliucr** [comment]
嗨！因为不是根据目标语言的验证集来选模型，zero-shot的variance可能会很大。你可以再多尝试跑几次模型来复现效果。

**Comment by xhr-catcher** [comment]
恩恩，好的，多谢您的回复啦！
